name: pullImage
on: 
   
    workflow_dispatch:  

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            
            - name: Run New Container
              run: |
                docker pull edwinasweeney/salarymodel:latest
                docker run -d --name salaryapp edwinasweeney/salarymodel:latest
                docker ps
                docker stop salaryapp
               
           

