name: CI

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout_code
      uses: actions/checkout@v6
    - name: clean_data
      run: |
          pwd
          cd ModelCleaning
          pip install pandas
          python Cleandata.py
    - name: train_model
      run: |
          pip install scikit-learn joblib
          python ModelCleaning/train_test_dataset.py

    

      
      
          