name: MLFlow 

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: Checkout_code
      uses: actions/checkout@v6
    - name: clean_data
      run: |
          pwd
          cd ModelCleaning
          pip install pandas
          python Cleandata.py

    - name: Open MLFlow
      run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
            mlflow server --host=0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

    - name: train_model
      run: |
          pip install scikit-learn joblib
          python ModelCleaning/train_test_dataset.py \
          --mlflow-tracking-uri http://localhost:5555
    
    - name: Cleanup MLFlow
      run: |
        docker stop mlflow-server
        docker rm mlflow-server
       
      
          
